### ISSUE TITLE
Website: Download page spacing might make it hard to notice `Integrate AppTelemetry` section

### ISSUE THREAD

**Issue by chadparker** [AppTelemetry/Viewer#110]
At my window size on a MacBook Pro the next section `Integrate AppTelemetry` is *barely* visible, and I almost missed it and probably would have if the window was just a tad shorter. Maybe less space between the two sections?

<img width="1187" alt="CleanShot 2021-05-19 at 08 30 52@2x" src="https://user-images.githubusercontent.com/438307/118841574-49973080-b87d-11eb-8b8f-60c014d8826e.png">

**Comment by winsmith** [comment]
Good point, thank you! Fixed :)
