### ISSUE TITLE
"date" param doesn't seem to display correctly when viewing Signal Data

### ISSUE THREAD

**Issue by lepolt** [AppTelemetry/Viewer#111]
I'm sending a date string as a signal parameter using an ISO8601 string, but when I view the Signal Data in the macOS or iOS apps, it appears to be truncating. 

Viewer 
![image](https://user-images.githubusercontent.com/669410/118976745-57af8480-b943-11eb-846e-b27971a21059.png)

Params payload
![image](https://user-images.githubusercontent.com/669410/118976654-3ea6d380-b943-11eb-96b1-dc1fcadc47b9.png)

**Comment by winsmith** [comment]
Just fixed this on the server. @lepolt could you confirm it's fixed please?

**Comment by lepolt** [comment]
🐛💥👍
Looks great! Thanks!
