### ISSUE TITLE
Simplify adding insight

### ISSUE THREAD

**Issue by mackoj** [AppTelemetry/Viewer#115]
Adding insight from signals is not easy on iOS you should consider adding a button for it.

**Comment by winsmith** [comment]
Hi, thanks for the feedback! Can you elaborate a bit? There's the "New Insight in {insight group name}" button at the bottom of each insight group, but I'm guessing that's what you mean by "it's not easy", right?

![IMG_B1CD18BBE489-1](https://user-images.githubusercontent.com/954120/121026826-c182b780-c7a6-11eb-9af1-b0ac10baec89.jpeg)

I'm still thinking a lot about how to structure insights better on iOS– do you have a suggestion of how a better UI would look like?

**Comment by mackoj** [comment]
Sorry for the lack of details I was thinking about the Recent Singal Screen but since I did understand better how the app works and thus don't think this is relevant anymore.

What I do think was complex to figure out is how to customise charts with custom signals.
