### ISSUE TITLE
Cannot rename insight group

### ISSUE THREAD

**Issue by jaanus** [AppTelemetry/Viewer#121]
Maybe same as #120, but happened on macOS, so reporting separately.

How to reproduce: have an Insight Group in macOS viewer. Try to click on the text field to rename the group.

Expected: focus is put on text field, can edit name of the group.

Observed: when I click in sidebar, it is closed, and I cannot edit the group name.

Is there a workaround?

https://user-images.githubusercontent.com/184253/122342416-490dba80-cf4d-11eb-8817-f9aa8debda69.mov

**Comment by winsmith** [comment]
No workaround right now, sorry. I just put in the wrong variable name for the text field, meaning the changes never get sent to the server. Next version will fix this of course.

**Comment by winsmith** [comment]
If you want to change the group's name RIGHT NOW, send me your app ID in the slack and I'll change it in the database :) sorry for the inconvenience

**Comment by jaanus** [comment]
Great, thank you. No urgency for now, I will wait for the update.
