### ISSUE TITLE
macOS Client hang when switching to Insights

### ISSUE THREAD

**Issue by timroesner** [AppTelemetry/Viewer#126]
Got a beachball and unrecoverable hang when trying to switch to the Insights tab.
Was able to capture a time profile trace with Instruments which is attached below. Still needs to be symbolicated though.

[Telemetry Profile.trace.zip](https://github.com/AppTelemetry/Viewer/files/6820641/Telemetry.Profile.trace.zip)

**Comment by timroesner** [comment]
This might be a dupe of #118 or #112. It's definitely an infinite loop that's causing the hang and possibly crash.
I'm able to repo this pretty consistently too.

**Comment by winsmith** [comment]
Thanks! The trace is also very helpful! I'm hoping the next version will be able to fix this.

**Comment by winsmith** [comment]
Hi @timroesner -- could you check if this still happens with Build 379? Thanks <3

**Comment by mgetto** [comment]
Hey, I'm on Build 383 and have the same or a similar issue.

I can go to Insights once. If I navigate to another view and then try to go back to Insights I get the beachball.

**Comment by winsmith** [comment]
Thanks! I'm really sorry about this... something about the way I structure my services does not agree with SwiftUI, or vice versa.

**Comment by timroesner** [comment]
Can confirm beachball issue is still happening with the latest build.
