### ISSUE TITLE
Can't edit second app in sidebar

### ISSUE THREAD

**Issue by maxbaeumle** [AppTelemetry/Viewer#136]
After updating to build 408 I can no longer edit my second app as the menu item appears as a section header and is not selectable.

<img width="1558" alt="Screenshot" src="https://user-images.githubusercontent.com/1935810/132003713-0d0ee17d-01c0-4f5c-af15-29e2d8ae374d.png">

**Comment by winsmith** [comment]
This is a macOS issue I'm constantly fighting to work around. Sorry about that -- until a new version comes out, try collapsing the first app section and see if that helps

**Comment by winsmith** [comment]
Can you check if this version fixes your issue please?

[Build 411](https://github.com/AppTelemetry/Viewer/files/7106069/Telemetry.Viewer.zip)

**Comment by maxbaeumle** [comment]
It does! Thanks.
