### ISSUE TITLE
First run: selecting something in the sidebar makes the "get started" view inaccessible

### ISSUE THREAD

**Issue by gormster** [AppTelemetry/Viewer#78]
Steps to reproduce:

1. Run the macOS app with a fresh account
2. Click "Help & Feedback"
3. Try to get back to the thing that said create a new app

If there's a way to do it, I couldn't figure it out. Well, I managed to do it once, by clicking the right sidebar icon in the toolbar, but then it didn't work when I tried again.

**Comment by winsmith** [comment]
Thanks for reporting, I'l check it out. For now, you can create new apps by clicking the (+) icon in the top of the left sidebar!
