### ISSUE TITLE
Feature: Would like to view a list of all received signals over a period of time with counts

### ISSUE THREAD

**Issue by lepolt** [AppTelemetry/Viewer#83]
👋 I use Firebase in my day job, but was looking for alternatives in a side project of mine... one thing I like about Firebase is that I can view all of my events (or signals in this case) and the number of times those events fired in a given period of time. 

I like this because it quickly enables me to see what users are doing most/least frequently, and provides a very quick overview of how users are generally using the app.

**Comment by winsmith** [comment]
Thanks so much! That's a neat idea and I'll put it in my queue! Could you maybe post a screenshot of how that looks in firebase? Are there different graphs for each event/signal type?

**Comment by lepolt** [comment]
Here's a screenshot from a Firebase demo project. The data I'm referring to is in a pretty simple, sortable table which includes the event name, number of times the event has fired, number of users who have fired the event, and a % change over time (although I use this the least and am not sure what the time frame is)
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/669410/117058391-8fd08980-acec-11eb-9642-3eac62cdfcd4.png">

**Comment by winsmith** [comment]
Huh, that's actually pretty close to the current lexicon view, it just needs a bit more metadata! Nice!
