### ISSUE TITLE
iOS widget is empty

### ISSUE THREAD

**Issue by biocross** [AppTelemetry/Viewer#92]
Firstly, thank you for building this amazing tool.

I've been using the iOS app from TestFlight, and just noticed the widget is empty. 

Maybe you were just trying it out (that's why it probably shows example code in the widget details), but you might want to remove it from the release scheme until it's ready :)

![image](https://user-images.githubusercontent.com/840512/117549988-2942c700-b070-11eb-8113-1aed2c740d12.png)

**Comment by winsmith** [comment]
Oh yes I totally forgot about the widget. It's completely empty and useless right now. I'll remove it from the scheme, thanks!
