### ISSUE TITLE
Swift-client-reference web page doesn't works

### ISSUE THREAD

**Issue by bubudrc** [AppTelemetry/Viewer#94]
Hi,
I'm using you awesome product and everything runs perfectly. The unique concern is that running in a mac app (Appkit) I got the log msg: 

> [Telemetry] On this platform, Telemetry can't generate a unique user identifier. It is recommended you supply one yourself. More info: https://apptelemetry.io/pages/telemetry-swift-client-reference.html

where the url https://apptelemetry.io/pages/telemetry-swift-client-reference.html doesn't works

**Comment by winsmith** [comment]
Whoops, thanks for noticing! The correct link should be https://apptelemetry.io/pages/signal-reference.html, I'll update the client ASAP.

**Comment by winsmith** [comment]
The problem behind this is that on macOS, we don't get the identifierForVendor method, which gives us a device id. For now, ideally you should either generate a unique UUID and store it in the UserDefaults, or use another distinct user identifier like an email address (don't worry, it gets hashed before it ever leaves the user's computer)

**Comment by bubudrc** [comment]
yep, I'm storing a UUID on UserDefault... thanks for your hard work and you quick reply :)

**Comment by winsmith** [comment]
Awesome, have fun, and don't hesitate to ask further questions
